### ISSUE TITLE
Problem with Spacy matcher

### ISSUE THREAD

**Issue by Bokkuren** [hetpandya/textgenie#4]
```
from textgenie import TextGenie

textgenie = TextGenie("hetpandya/t5-small-tapaco", "bert-base-uncased")
sentences = [
    "The video was posted on Facebook by Alex.",
    "I plan to run it again this time",
]
x = textgenie.magic_lamp(
    sentences, "paraphrase: ", n_mask_predictions=5, convert_to_active=True
)

print(x)
```

There seems to be a problem with active voice conversion. This is the code I'm running and this is the error:

`Traceback (most recent call last):
  File "test2.py", line 11, in <module>
    sentences, "paraphrase: ", n_mask_predictions=5, convert_to_active=True
  File "\lib\site-packages\textgenie\textgenie.py", line 240, in magic_lamp
    convert_to_active,
  File "\lib\site-packages\textgenie\textgenie.py", line 136, in magic_once
    active_voice = self.convert_to_active(sent)
  File "\lib\site-packages\textgenie\textgenie.py", line 108, in convert_to_active
    if is_passive(sent):
  File "\lib\site-packages\textgenie\grammar_utils.py", line 280, in is_passive
    matcher.add("Passive", None, passive_rule)
  File "spacy\matcher\matcher.pyx", line 76, in spacy.matcher.matcher.Matcher.add
TypeError: add() takes exactly 2 positional arguments (3 given)`

**Comment by hetpandya** [comment]
Hi @Bokkuren, sorry for the late response. The `add()` needs just 2 parameters from `v3.0` and above. I've fixed the issue by using `spacy==2.2.4`
